install.packages("tidyverse")
library(tidyverse)
data <- read.csv(file.choose())
View(data)
head(data)
str(data)
summary(data)
sum(is.na(data))
data <- data %>% select(-CustomerID)
names(data)
data$Genre <- as.numeric(factor(data$Genre))
cor(data)
pairs(data)
ggplot(data, aes(x = as.factor(Genre), y = Spending.Score..1.100.)) + 
  geom_boxplot() +
  labs(x = "Genre", y = "Spending Score")
data_scaled <- scale(data)
install.packages("factoextra")
library(factoextra)
fviz_nbclust(data_scaled, kmeans, method = "wss")
set.seed(123)
k <- 5
kmeans_result <- kmeans(data_scaled, centers = k, nstart = 25)
data$Cluster <- as.factor(kmeans_result$cluster)
fviz_cluster(kmeans_result, data = data_scaled, ellipse.type = "convex", geom = "point", stand = FALSE)
aggregate(. ~ Cluster, data = data, mean)
write.csv(data, "customer_segments.csv", row.names = FALSE)